import Head from 'next/head';

import styles from '@/styles/Home.module.css';


const Home = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
    <main className={styles.main}>
      <h1 className="text-2xl font-bold underline">
        Hello world!
      </h1>
    </main>
  </>
);

export default Home;
